[workspace]
members = [
    'Exploiting path mapping for web cache deception',
    'Exploiting path delimiters for web cache deception',
    'Exploiting origin server normalization for web cache deception',
    'Exploiting cache server normalization for web cache deception'
]
