[workspace]
members = [
    'Excessive trust in client-side controls',
    'Flawed enforcement of business rules',
    'High-level logic vulnerability',
    'Inconsistent security controls',
    'Inconsistent handling of exceptional input',
    'Weak isolation on dual-use endpoint',
    'Insufficient workflow validation',
    'Authentication bypass via flawed state machine',
    'Infinite money logic flaw',
    'Authentication bypass via encryption oracle',
    'Bypassing access controls using email address parsing discrepancies'
]
